language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ds28/docker-react -f Dockerfile.dev .

script:
  - docker run ds28/docker-react npm test -- --watchAll=false
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-616507080034"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
